version: 2
updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: fix
      prefix-development: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
