name: publish-package
on:
  release:
    types:
      - published
permissions:
  contents: read
  id-token: write
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@faergeek/monads
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          registry-url: https://registry.npmjs.org/
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm publish --access public --no-git-checks --provenance
