name: pull-request
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec commitlint --verbose --from="remotes/origin/$GITHUB_BASE_REF"
      - name: update changelog
        run: |
          pnpm exec git-cliff -o
          pnpm exec prettier --write CHANGELOG.md
          git add CHANGELOG.md

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git commit -m 'chore: update changelog'; then
            git push origin
          fi
