name: pull-request
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec commitlint --verbose --from="remotes/origin/$GITHUB_BASE_REF"
      - name: update changelog
        run: |
          pnpm exec git-cliff -o
          pnpm exec prettier --write CHANGELOG.md
          git add CHANGELOG.md

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git commit -m 'chore: update changelog'; then
            git push origin
          fi
