name: pull-request
on:
  - pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        with:
          cache: true
          run_install: true
      - uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
      - run: pnpm exec commitlint --verbose --from="remotes/origin/$GITHUB_BASE_REF"
      - name: update changelog
        run: |
          pnpm exec git-cliff -o
          pnpm exec prettier --write CHANGELOG.md
          git add CHANGELOG.md

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          if git commit -m 'chore: update changelog'; then
            git push origin
          fi
