name: push
on:
  push:
    branches:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: read
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format:check
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm test
  publish-to-latest:
    if: github.ref_name == github.event.repository.default_branch
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: asdf-vm/actions/install@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: bump version
        run: |
          version=$(pnpm exec git-cliff --bumped-version)

          if pnpm version --no-git-tag-version "$version"; then
            pnpm exec git-cliff --bump -o
            pnpm exec prettier --write CHANGELOG.md
            git add CHANGELOG.md package.json

            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git commit -m "chore: $version"
            git push origin

            git tag "$version"
            git push origin --tags
          fi
